#!/bin/sh
# Build Kali NetHunter Pro for the Samsung Galaxy S20 FE 5G (r8q) from scratch.
#
# Requirements on the host: git, curl, patch, podman (or docker) with KVM
# access, and img2simg (android-tools).
#
# Output: kali-nethunter-pro/output/
#   bootimg-r8q               Android boot image generated by the r8q recipe
#   *.rootfs.simg             root filesystem for `fastboot flash userdata`
set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
NHP="$HERE/kali-nethunter-pro"
UPSTREAM="https://github.com/ben443/nethunter-pro-sm8450.git"
COMMIT="$(cat "$HERE/nethunter-pro/UPSTREAM_COMMIT")"

command -v img2simg >/dev/null || { echo "img2simg not found (install android-tools)"; exit 1; }

# 1. NetHunter Pro build scripts with r8q support at a known commit
if [ ! -d "$NHP" ]; then
	git clone "$UPSTREAM" "$NHP"
	git -C "$NHP" checkout -q "$COMMIT"
fi

# 2. Kernel package
"$HERE/kernel/build-kernel.sh"
cp -f "$HERE"/kernel/out/linux-image-*_arm64.deb "$NHP/devices/qcom/packages/"

# 3. Patched phoc (GPU thumbnails with simpledrm), installed over Kali's
"$HERE/phoc/build-phoc.sh"
cp -f "$HERE"/phoc/out/phoc_*_arm64.deb "$NHP/devices/qcom/packages/"

# 4. Image (Kali rolling + Phosh)
cd "$NHP"
./build.sh -t r8q -e phosh "$@"

# 5. fastboot needs an Android sparse image (the build container has no img2simg)
cd "$NHP/output"
for img in *.rootfs.img; do
	img2simg "$img" "${img%.img}.simg" 4096
done

ls -l "$NHP"
